### ISSUE TITLE
[Bug]: platform compatibility issue

### ISSUE THREAD

**Issue by aacebedo** [jetpack-io/devbox#1466]
**Current Behavior (bug)**
I try to install "plantuml@latest" package. It fails telling there is no platform compatible (I am running NixOS).
I think it comes from the fact the package has only "unix" as a platform.
Removing the "latest" from the package makes it work.

**Expected Behavior (fix)**
Installing plantuml@latest shall work on NixOS

**Additional context**
```
Version:     0.5.13
Platform:    linux_amd64
Commit:      none
Commit Time: unknown
Go Version:  go1.20.4
Launcher:
```

**Comment by mikeland73** [comment]
@aacebedo the issue you are running into is because the result for @latest is actually very old
<img width="1316" alt="image" src="https://github.com/jetpack-io/devbox/assets/544948/a7575a17-56e1-45c5-ad0c-9b94ae2ee831">

We need to change how we sort packages because nix doesn't always have consistent versioning. 

cc: @gcurtis

**Comment by gcurtis** [comment]
This should be fixed now that `plantuml@latest` resolves to the real latest version.
