### ISSUE TITLE
[Bug]: Fail to link .zshenv and .zprofile - invalid cross-device link

### ISSUE THREAD

**Issue by gmontanola** [jetpack-io/devbox#1536]
**Current Behavior (bug)**
```
2023/10/06 09:42:17 Error linking zsh setting file from /home/gmontanola/.zshenv to /tmp/devbox1606281637/.zshenv: link /home/gmontanola/.zshenv /tmp/devbox1606281637/.zshenv: invalid cross-device link
2023/10/06 09:42:17 Error linking zsh setting file from /home/gmontanola/.zprofile to /tmp/devbox1606281637/.zprofile: link /home/gmontanola/.zprofile /tmp/devbox1606281637/.zprofile: invalid cross-device link
```

**Expecteed Behavior (fix)**

Files are copied instead of linked. Are there any drawbacks with this approach?

**Additional context**

```Version:     0.6.0
Platform:    linux_amd64
Commit:      fdbd72f230b3520dde60d72c57d9460922ade656
Commit Time: 2023-10-03T18:04:08Z
Go Version:  go1.21.1
Launcher:    0.2.0
```

My **/tmp** is mounted as `tmpfs` filesystem. I can disable this by masking [tmp.mount](https://github.com/systemd/systemd/blob/main/units/tmp.mount).

**Comment by Lagoja** [comment]
Hey @gmontanola, thanks for reporting! are you using the Docker (tmpfs mount)[https://docs.docker.com/storage/tmpfs/]? 

We currently link the zshrc/profiles so that devbox can pick up the changes you make to your profile without having to restart, but it looksl ike linking is disallowed on the mounted temp directory. 

Something we're looking at for an upcoming release is getting rid of the link and actually copying the files, so that this sort of scenario won't break.

**Comment by gmontanola** [comment]
> are you using the Docker

Not using Docker. It's just a simple SystemD unit that mounts /tmp using `tmpfs`.

> Something we're looking at for an upcoming release is getting rid of the link and actually copying the files, so that this sort of scenario won't break.

Great! It's a minor issue and non-blocking but really nice to hear this :)
