### ISSUE TITLE
Can devbox have latest Clang and latest GCC from git? 

### ISSUE THREAD

**Issue by osevan** [jetpack-io/devbox#16]
Devbox supporting latest gcc git or clang git compiles? 

Thanks and

Best regards

**Comment by loreto** [comment]
Hi @osevan, right now, we can use any version in nixpkgs including the "Unstable" channel (make sure to look there too, since some times the newest versions of packages are there).

That means the latest versions you can pick of those packages are:
- Version 12.2.0 for `gcc` via the [gcc12](https://search.nixos.org/packages?channel=unstable&show=gcc12&from=0&size=50&sort=relevance&type=packages&query=gcc) package.
- Version 14.0.6 for `clang` via the [clang_14](https://search.nixos.org/packages?channel=unstable&show=clang_14&from=0&size=50&sort=relevance&type=packages&query=clang) package.

Do those suit your needs?

If you truly need to build from HEAD or a specific revision in the github repo, then we don't support that right now, but we are working on this https://github.com/jetpack-io/devbox/issues/21 feature which should allow something close.

**Comment by osevan** [comment]
Thank you very much.


Weekly builds will be nice

**Comment by Lagoja** [comment]
Closing this issue, and tracking this as part of issue #21. Thank you!
