### ISSUE TITLE
Questions from a New User

### ISSUE THREAD

**Issue by evanleck** [jetpack-io/devbox#1643]
Hi all,

First off, thanks for building and sharing devbox! I have two questions as I'm starting to migrate my existing setup to devbox:

1. How do you recommend using a shell installed with devbox as the user's default shell? I currently install fish via Homebrew and add the path to `/etc/shells`, but as I understand it, the path to fish as installed by devbox won't be that stable, right?
2. How do you recommend installing and loading plugins for other packages like tmux? Specifically, I'm trying to install https://github.com/catppuccin/tmux via devbox and the `tmuxPlugins.catppuccin` package rather than using tpm but I can't figure out how to get the plugin loaded once it's installed.

Thanks a bunch!

**Comment by empjustine** [comment]
> How do you recommend using a shell installed with devbox as the user's default shell?

Don't do this.

Nix might garbage collects store paths if they're not being used. This means if you do something that invalidates your garbage collection roots (say, for example, something moves or removes the folder where your devbox with your shell is is by mistake) you lose your shell.

My suggestion: 

* look at what version of the shell you want at https://www.nixhub.io/
* Install it using the "nix flakes profile install" method: `nix --extra-experimental-features 'nix-command flakes' profile install ${NIXHUB_REFERENCE_HERE}`.

> the path to fish as installed by devbox won't be that stable, right?

The path is stable and read-only (it should point to something inside `/nix/store/${hash}-${pname}-${version}`) the real issue is the possibility of it being garbage-collected as mentioned earlier.

---

> How do you recommend installing and loading plugins for other packages like tmux?

If you're using the "nix flakes profile install" method mentioned earlier, the plugin will show here: `~/.nix-profile/share/tmux-plugins/catppuccin/`. No clue how to get the plugin to actually work from here - I don't mess with tmux plugins myself. Some naive searches returned that you're supposed to source the correct conf files from `~/.tmux.conf` with something like `source-file ~/.nix-profile/share/tmux-plugins/catppuccin/catppuccin-mocha.tmuxtheme` and `run ~/.nix-profile/share/tmux-plugins/catppuccin/catppuccin.tmux`.)

If you're hellbent on using devbox for this, you can find whatever you `add` to a devbox in `.devbox/virtenv/.wrappers/`. This is a implementation detail and might break in future versions of devbox.

**Comment by Lagoja** [comment]
If you want to install the tmux globally using Devbox, I recommend using `devbox global add zsh`, which will install it to a central Devbox profile that can be used across all your projects. You can then activate your global packages by adding 
```
eval "$(devbox global shellenv --init-hook)"
```
to the top of your shellrc. For more details, check out our [Docs](https://www.jetpack.io/devbox/docs/devbox_global/)

> Nix might garbage collects store paths if they're not being used. This means if you do something that invalidates your garbage collection roots (say, for example, something moves or removes the folder where your devbox with your shell is is by mistake) you lose your shell.

This is not true if you use `devbox global`.  Global packages will be installed in a fixed directory (`devbox global path`) which should not move (unlike project directories). Devbox also creates a nix-profile as part of the generated project, so the package will not be garbage collected.

> How do you recommend installing and loading plugins for other packages like tmux?

If you install the tmux plugin in your global profile (using `devbox global add tmuxPlugins.catppucin`), then the plugin will be found at `$(devbox global path)/.devbox/nix/profile/default/share/tmux-plugins`. you can then source it from that location to your tmux.conf

**Comment by evanleck** [comment]
Thanks for the insight! I've gotten around installing and using Fish shell by not making it my login shell, which works fine. And I've been able to add and source plugins just fine using a similar approach to https://github.com/lilyball/nix-env.fish/tree/master.
