### ISSUE TITLE
Specify package versions

### ISSUE THREAD

**Issue by timonmasberg** [jetpack-io/devbox#20]
Hi, currently it is not clear how to install a specific package version for example for nodejs 16 instead of the latest 18 which is the version for the `nodejs` nix package. Is there a way to do this?  This seems to be a must-have thing for dev environments. After some research, this [tool](https://lazamar.co.uk/nix-versions) came up, which feels like more of a workaround...

Nevertheless, thanks for the tool!

**Comment by loreto** [comment]
Hi @timonmasberg: you should be able to specify any version available in [nixpkgs](https://search.nixos.org/packages?channel=22.05&from=0&size=50&sort=relevance&type=packages&query=nodejs).

For example, `nodejs-16_x` is one of the options listed if you want nodejs 16. There's also `nodejs-10_x`, `nodejs-12_x`, etc. Does that answer your question?

**Comment by timonmasberg** [comment]
Thanks, these are, as far as i understand, own packages. But for example, for Dapr, there exists only [one package](https://search.nixos.org/packages?channel=unstable&show=dapr-cli&from=0&size=50&sort=relevance&type=packages&query=dapr). How would I be able to pick a version there. 

Thanks for the help!

**Comment by loreto** [comment]
Ah, got it. Yes, right now a package with the version you want needs to exist in nixpkgs. In the case of `dapr`, because there's only a single `dapr` package, that's the only option you have (at the moment).

We are working on a feature that would let you add packages directly from github (in addition to the packages from nixpkgs). That would make it possible to grab the package directly from `https://github.com/dapr/dapr` and you could then specify any version you want, since dapr has all the releases there.

Unfortunately that feature is not ready yet, but I will update this ticket once we have it in place.

**Comment by timonmasberg** [comment]
Understood, thanks for the clarification. Really looking forward to using the GitHub feature!
