### ISSUE TITLE
Feature Request: Extend the CLI to generate a `devcontainer.json` file

### ISSUE THREAD

**Issue by mikenikles** [jetpack-io/devbox#338]
In version 0.0.3 of the VS Code extension ([marketplace link](https://marketplace.visualstudio.com/items/jetpack-io.devbox/changelog)) you added the ability to generate a `devcontainer.json` file :tada:.

It would be great to have this command available in the `devbox` CLI as well. With that, one could automate the `devcontainer.json` generation as part of a setup process for contributors who want to use GitHub Codespaces.

**Comment by mohsenari** [comment]
@mikenikles Thanks for the suggestions. That's not a bad idea! We are looking to deprecate `devbox build` for many reasons, one being, it was causing a lot of errors for users who wanted to convert the devbox env to a container. Because we were trying to conveniently generate a dockerfile but it would only work in specific use cases.
We can replace that approach with generating devcontainer.json + a dockerfile and let users customize and generate their own containers. Two birds, one stone! 
I'll keep this issue open to track and will update here once we make the CLI command available.

**Comment by mohsenari** [comment]
@mikenikles 
Update: I merged a PR that allows for 2 CLI commands:
`devbox generate devcontainer` and `devbox generate dockerfile`
devcontainer behaves the same as the vscode extension.
dockerfile generates a dockerfile that lets you run the shell environment inside a container.

Will close the issue when next release is out.

**Comment by mikenikles** [comment]
Exciting news, I'll check that out when it's released.

Thanks for getting this done and letting me know!

**Comment by Lagoja** [comment]
Added to an upcoming release, should be available soon!

**Comment by Lagoja** [comment]
Released in 0.2.0
