### ISSUE TITLE
[Cloud]: Add support for vscode remote extensions

### ISSUE THREAD

**Issue by pomdtr** [jetpack-io/devbox#585]
I really like to use vscode remote extensions to code in cloud environments, but the `remote SSH` extension does not work in devbox cloud vms (see https://nixos.wiki/wiki/Visual_Studio_Code#Remote_SSH for potential fixes).

Alternatively, I succeeded to launch the vscode server using the following command:

```bash
curl -L 'https://code.visualstudio.com/sha/download?build=stable&os=cli-alpine-x64' -o /tmp/vscode_cli_alpine_x64_cli.tar.gz \
  && mkdir -p ~/.local/bin \
  && tar -zxf /tmp/vscode_cli_alpine_x64_cli.tar.gz  --directory ~/.local/bin \
  && ~/.local/bin/code tunnel
```

I feel like having the vscode process running in the vm is a far better experience than just relying on the file syncing mechanism. Maybe a flag could be added to the cloud shell command to automatically install it ?

**Comment by mohsenari** [comment]
More context:
The issue seems to be vscode looking for certain binaries (e.g. node) in remote host in `~/.vscode-server/bin/e2816fe719a40.../`. But in devbox cloud we point the installed binaries to `./.devbox/profile/default/bin/`.
So the workaround is first, make sure to have `nodejs-16_x` added in devbox.json packages and second, to create symlinks from where vscode-server expects the binaries to be, to devbox binaries.
```shell
ln -sf $(which node) ~/.vscode-server/bin/e2816fe719a40<omitted hash>.../node` 
```

**Comment by pomdtr** [comment]
This package automate this process, but is not available in nixpkgs: https://github.com/msteen/nixos-vscode-server
