### ISSUE TITLE
[Bug]: Devbox looses env vars.

### ISSUE THREAD

**Issue by gfriloux** [jetpack-io/devbox#694]
**Current Behavior (bug)**
With `devbox 0.3.3` i could use `devbox` inside `gitlab-ci` to be sure to have the same env than devs.
Today i moved to `devbox 0.4.1`, and once `devbox` is ran, every ENV variable set by `gitlab-ci` will be lost.
This is an issue when you need to set secrets through ENV.

**Expected Behavior (fix)**
Variables set BEFORE loading `devbox` (from `CI` for example) should remain.
Is it a wanted behavior (feature) since `0.4.0`?

**Additional context**
-

**Comment by gfriloux** [comment]
I made a wonderful CI conf with a `.gitlab-ci.yml` file containing only that kind of things:
```yaml
deploy:
  stage: deploy
  image: xxx/devbox:latest
  script:
    - devbox shell -- just deploy
  only:
    - tags
  cache:
    <<: *global_cache

backupsmite:
  stage: conformity
  image: xxx/devbox:latest
  rules:
    - if: $WHICH_SCHEDULE == "backupsmite"
  script:
    - devbox shell -- just validate


keysmite:
  stage: conformity
  image: xxx/devbox:latest
  rules:
    - if: $WHICH_SCHEDULE == "keysmite"
  script:
    - devbox shell -- just keys_sync
```

We then use `just` (https://github.com/casey/just) to set everything (using `rbw` to retrieve secrets if missing from ENV):
```make
set dotenv-load := true

# Will fetch secrets if needed. Creates .env file!
@secrets:
	mkdir -p etc/keys
	# First, we see if secrets are propagated through ENV
	[[ "${ENV_VARS+x}"        != "x"                  ]] || echo "${ENV_VARS}"        >".env"
	[[ "${SSH_KEY+x}"         != "x"                  ]] || echo "${SSH_KEY}"         >"etc/keys/process@gitlab.xxx.fr"
	[[ "${S3_DEV+x}"          != "x"                  ]] || echo "${S3_DEV}"          >"etc/keys/s3cfg-dev"
	[[ "${S3_PROD+x}"         != "x"                  ]] || echo "${S3_PROD}"         >"etc/keys/s3cfg-prod"
	...
	
	# Then, we will fetch any missing secret from Vault
	[[ -f .env                                        ]] || rbw get infrastructure/socoda/exploitation/mgmt >".env"
	[[ -f "etc/keys/s3cfg-dev"                        ]] || rbw get s3cmd_dev                        >"etc/keys/s3cfg-dev"
	[[ -f "etc/keys/s3cfg-prod"                       ]] || rbw get s3cmd_prod                       >"etc/keys/s3cfg-prod"


# Only run this if you have the .env file
@insanity:
	[[ -n "${REMOTE_LOGIN}"                           ]]
	[[ -n "${REMOTE_HOST}"                            ]]
	[[ -n "${KJK_CONF_ONLY_ERRORS}"                   ]]
	[[ -n "${KJK_CONF_SLACK_URL}"                     ]]
	[[ -n "${OS_AUTH_URL}"                            ]]
	[[ -n "${OS_IDENTITY_API_VERSION}"                ]]
	[[ -n "${OS_USER_DOMAIN_NAME}"                    ]]
	[[ -n "${OS_PROJECT_DOMAIN_NAME}"                 ]]
	[[ -n "${OS_TENANT_ID}"                           ]]
	[[ -n "${OS_TENANT_NAME}"                         ]]
	[[ -n "${OS_USERNAME}"                            ]]
	[[ -n "${OS_PASSWORD}"                            ]]
	[[ -n "${OS_REGION_NAME}"                         ]]
	[[ -f "etc/slack-backup.conf"                     ]] || echo "${SLACK_BACKUP}"    >"etc/slack-backup.conf"
	[[ -f "etc/slack-keys.conf"                       ]] || echo "${SLACK_KEYS}"      >"etc/slack-keys.conf"
	[[ $(which jq bc openstack shellcheck)            ]]
	chmod 0600 etc/keys/*

# We securely delete any file that holds secrets!
@ragnarok:
	shred -uz .env                                      2>&1 >/dev/null
	shred -uz etc/slack-backup.conf                     2>&1 >/dev/null
	shred -uz etc/slack-keys.conf                       2>&1 >/dev/null
	shred -uz etc/keys/s3cfg-dev                        2>&1 >/dev/null
	shred -uz etc/keys/s3cfg-prod                       2>&1 >/dev/null

# Check code quality
@check:
	find . -name '*.sh' -not -name 'framework.sh' -not -name 'kojak.sh' -not -path '*.devbox*' | xargs shellcheck -x

@test: check
	./tests/tests.sh

@rapport: check secrets
	just _rapport
	just ragnarok

# Choose servers to backup
@backup: check secrets
	ls etc/serveurs/ | sed 's:.conf::g' | gum choose --cursor "🪄" --cursor-prefix="🤎" --unselected-prefix="🤍 " --selected-prefix="💖 " --no-limit --height=25 | xargs -I {} just _backup {} daily
	just ragnarok

# Check backups
@validate: check secrets
	just _validate
	just ragnarok

# Check ssh keys
@keys_sync: check secrets
	just _keys_sync
	just ragnarok

# Deploy latest version to MGMT server
@deploy: test secrets
	just _deploy
	just ragnarok

_rapport: insanity
	{{justfile_directory()}}/scripts/backup/rapport.sh

_deploy: insanity
	rsync -e "ssh -i etc/keys/process@gitlab.xxxx.fr" -avzr --exclude ".git" --exclude "validation" --exclude "tests" --exclude "README.md" --exclude "update.sh" --exclude "Justfile" --delete-after * $REMOTE_LOGIN@$REMOTE_HOST:/xxx/

_validate: insanity
	./validation/backup.sh

_keys_sync: insanity
	./validation/devs.sh

_backup SERVER TYPE: insanity
	{{justfile_directory()}}/scripts/backup/instance.sh -c {{justfile_directory()}}/etc/serveurs/{{SERVER}}.conf {{TYPE}}
```

**Comment by Lagoja** [comment]
Hey @gfriloux, thanks for reporting! We've been trying to strike the right balance between isolation and flexibility for Devbox, let me share a bit of context on what changed in 0.4.1

In earlier versions of Devbox, we did not use the host environment to create the shell environment when running `devbox shell`. Instead, we would create a new shell session and environment based on the user's shellrc + the contents of their `devbox.json.` However, a bug in `devbox run` and `devbox shell -- <cmd>` would leak variables from the user's host environment, which is why your `gitlab-ci` worked the way it did.

Starting in 0.4.0, we unified how these commands create their environments, meaning that `run` and `shell --` no longer used the environment variables set in the host. This improved isolation and reproducibility for Devbox projects but also broke a lot of use cases like yours that relied on Devbox having access to the host's environment variables. 

Based on customer feedback, we're planning a couple more tweaks in an upcoming release: 

1. By default, we'll retain the host's environment when starting a Devbox shell. This means the environment variables you're setting in `gitlab-ci` should be available in Devbox if you run it normally. 
2. We'll also offer an `isolated` mode for Devbox. This will clear your environment and not source the user's shellrc when starting your shell or running your scripts. This will be useful for developers that want to ensure their environment is fully isolated and reproducible.
3. As part of this `isolated` mode, we'll let users allow users to configure environment variables from the host shell that they want to pass into devbox.

For your CI use case -- this means that you should use the workaround for now, but we'll restore the earlier behavior in an upcoming release. I'll link any related PRs to this issue.

**Comment by gfriloux** [comment]
Thanks for taking the time to explain me theses!
It's all clear, and i know what to do, thus, i close this issue!
