### ISSUE TITLE
Can multiple projects with a database service run at the same time?

### ISSUE THREAD

**Issue by Vandaahl** [jetpack-io/devbox#705]
I would like to use Devbox as a LAMP stack with each project having its own stack with (mostly) the same services. But if I start a stack with a SQL database server more than once, the ones after the first one will fail due to the error "Can't connect to the local server through socket '/blabla/devbox.d/mysql/mysql.sock'". 

Can you only start one instance of the database service at a time? Is this a nix limitation? Or is there something I can configure to overcome this?

**Comment by Lagoja** [comment]
Hey @Vandaahl

Currently this is not possible. This is partly a Nix limitation, since Nix installs the packages on your local machine, and they share the same network.

We're investigating how we can provide an option to isolate shells at the network level, and we're open to suggestions on how this could be achieved, or what an ideal interface would look like.

For now, some workarounds include: 

- Run a single SQL DB Server (perhaps in it's own Devbox project), and connect your projects to it
- Run the projects in a devcontainer (use `devbox generate devcontainer` to get the right config files) to isolate them.

**Comment by Vandaahl** [comment]
> * Run a single SQL DB Server (perhaps in it's own Devbox project), and connect your projects to it

This seems like an acceptable workaround for now. I'll have to think of a way to start this database project from another project so I don't have to separately start it each time.

**Comment by Lagoja** [comment]
Closing this for now, will reopen a future issue when we work on built-in network isolation
