### ISSUE TITLE
[Bug]: another `devbox` binary is used

### ISSUE THREAD

**Issue by hezhizhen** [jetpack-io/devbox#781]
**Current Behavior (bug)**

<img width="1101" alt="Screenshot 2023-03-17 at 13 28 37" src="https://user-images.githubusercontent.com/7611700/225820630-f952c1f7-368a-48cd-8aac-04af55705a34.png">

I want to use the binary in `/usr/local/bin` whose version is `0.4.4`, but it seems that the binary in `dist` is used.

**Expected Behavior (fix)**

Use the former `devbox` instead of the latter one.

**Additional context**

**Comment by gcurtis** [comment]
This has thrown me off too. I tend to build and run with `go install ./cmd/devbox && devbox` which puts it in my `$GOBIN` directory. I didn't realize I had been running an old `dist/devbox` binary instead.

The reason is because `devbox.json` sets `PATH=$(pwd)/dist:$PATH` in the init hooks. @mikeland86 is it okay to remove this? I think it's a bit surprising if you don't know about it.

**Comment by Lagoja** [comment]
I think it makes sense to remove it. It's convenient, but easy to miss and pretty unexpected.

**Comment by hezhizhen** [comment]
> This has thrown me off too. I tend to build and run with `go install ./cmd/devbox && devbox` which puts it in my `$GOBIN` directory. I didn't realize I had been running an old `dist/devbox` binary instead.
> 
> The reason is because `devbox.json` sets `PATH=$(pwd)/dist:$PATH` in the init hooks. @mikeland86 is it okay to remove this? I think it's a bit surprising if you don't know about it.

Oh, I forgot it...
